import type { APIRoute } from 'astro';

export const GET: APIRoute = () => {
  // Redirect old /sitemap.xml requests to the new sitemap generated by @astrojs/sitemap
  // Note: The sitemap files are only generated in production builds.
  return new Response(null, {
    status: 308,
    headers: { Location: '/sitemap-index.xml' },
  });
};
